
name: GitHub Webhook Trigger

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, closed]
  merge_group:
    types: [created, closed]

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        uses: actions/http-request@v3
        with:
          url: 'http://your-flask-app-url/webhook'   # Replace this with your actual Flask app URL
          method: 'POST'
          data: |
            {
              "event_type": "${{ github.event_name }}",
              "repository_name": "${{ github.repository }}",
              "ref": "${{ github.event.ref }}"
            }
          headers: '{"Content-Type": "application/json"}'
